/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smegi.coffeeshop;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.CompoundBorder;

/**
 *
 * @author Pakijaner
 */
public class CoffeeShop extends javax.swing.JFrame {

    /**
     * Creates new form CoffeeShop
     */
    public CoffeeShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_main = new javax.swing.JPanel();
        javax.swing.JPanel panel_login = new JPanelBackground("/backgrounds/background.jpg");
        login_loginWithLabel = new javax.swing.JLabel();
        panel_login_container = new javax.swing.JPanel();
        login_usernameField = new javax.swing.JTextField();
        login_passwordField = new javax.swing.JTextField();
        login_loginButton = new javax.swing.JButton();
        panel_login_container_register = new javax.swing.JPanel();
        login_createAccountButton = new javax.swing.JButton();
        login_forgotPasswordButton = new javax.swing.JButton();
        panel_register = new JPanelBackground("/backgrounds/coffeebackground.jpg");
        panel_register_container = new javax.swing.JPanel();
        register_usernameField = new javax.swing.JTextField();
        register_passwordField = new javax.swing.JTextField();
        register_emailField = new javax.swing.JTextField();
        register_registerButton = new javax.swing.JButton();
        register_backToLoginButton = new javax.swing.JButton();
        panel_coffeeList = new JPanelBackground("/backgrounds/bgr.jpg");
        jButton1 = new javax.swing.JButton();
        panel_coffeelist_left = new javax.swing.JPanel();
        coffeelist_coffeelisLabel = new javax.swing.JLabel();
        panel_coffeelist_center = new javax.swing.JPanel();
        panel_header = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_row1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panel_row2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        panel_row3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        panel_row4 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        panel_row5 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        panel_row6 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        panel_orderReview = new javax.swing.JPanel();
        panel_rate = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("loginFrame"); // NOI18N

        panel_main.setMinimumSize(new java.awt.Dimension(0, 0));
        panel_main.setPreferredSize(new java.awt.Dimension(480, 800));
        panel_main.setLayout(new java.awt.CardLayout());

        panel_login.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 50, 10, 50));
        panel_login.setPreferredSize(new java.awt.Dimension(480, 800));
        panel_login.setLayout(new java.awt.BorderLayout());

        login_loginWithLabel.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        login_loginWithLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_loginWithLabel.setText("login with");
        panel_login.add(login_loginWithLabel, java.awt.BorderLayout.CENTER);

        panel_login_container.setOpaque(false);
        panel_login_container.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        login_usernameField.setBackground(new Color(0,0,0,0));
        login_usernameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_usernameField.setText("Username");
        login_usernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        login_usernameField.setMargin(new java.awt.Insets(0, 20, 0, 20));
        login_usernameField.setMinimumSize(new java.awt.Dimension(40, 24));
        login_usernameField.setOpaque(false);
        login_usernameField.setPreferredSize(new java.awt.Dimension(40, 40));
        panel_login_container.add(login_usernameField);

        login_passwordField.setBackground(new Color(0,0,0,0));
        login_passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_passwordField.setText("Password");
        login_passwordField.setToolTipText("");
        login_passwordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        login_passwordField.setMargin(new java.awt.Insets(0, 20, 0, 20));
        login_passwordField.setOpaque(false);
        login_passwordField.setPreferredSize(new java.awt.Dimension(40, 19));
        panel_login_container.add(login_passwordField);

        login_loginButton.setBackground(new java.awt.Color(255, 255, 255));
        login_loginButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_loginButton.setText("Login");
        login_loginButton.setToolTipText("");
        login_loginButton.setBorder(new CompoundBorder(
            BorderFactory.createEmptyBorder(10, 50, 0, 50), 
            BorderFactory.createMatteBorder(0,0,2,0 , Color.BLACK)));
    login_loginButton.setContentAreaFilled(false);
    login_loginButton.setMargin(new java.awt.Insets(20, 20, 20, 20));
    login_loginButton.setPreferredSize(new java.awt.Dimension(29, 10));
    login_loginButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            login_loginButtonActionPerformed(evt);
        }
    });
    panel_login_container.add(login_loginButton);

    panel_login_container_register.setOpaque(false);
    panel_login_container_register.setLayout(new java.awt.GridLayout(1, 0, 100, 0));

    login_createAccountButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    login_createAccountButton.setText("Create an account");
    login_createAccountButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    login_createAccountButton.setContentAreaFilled(false);
    login_createAccountButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            login_createAccountButtonActionPerformed(evt);
        }
    });
    panel_login_container_register.add(login_createAccountButton);

    login_forgotPasswordButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    login_forgotPasswordButton.setText("Forgot password");
    login_forgotPasswordButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    login_forgotPasswordButton.setContentAreaFilled(false);
    panel_login_container_register.add(login_forgotPasswordButton);

    panel_login_container.add(panel_login_container_register);

    panel_login.add(panel_login_container, java.awt.BorderLayout.SOUTH);

    panel_main.add(panel_login, "card_login");

    panel_register.setLayout(new java.awt.BorderLayout());

    panel_register_container.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 100, 200, 100));
    panel_register_container.setOpaque(false);
    panel_register_container.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

    register_usernameField.setBackground(new Color(0,0,0,0));
    register_usernameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    register_usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    register_usernameField.setText("Username");
    register_usernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    register_usernameField.setMargin(new java.awt.Insets(0, 20, 0, 20));
    register_usernameField.setMinimumSize(new java.awt.Dimension(300, 24));
    register_usernameField.setOpaque(false);
    register_usernameField.setPreferredSize(new java.awt.Dimension(88, 40));
    panel_register_container.add(register_usernameField);

    register_passwordField.setBackground(new Color(0,0,0,0));
    register_passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    register_passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    register_passwordField.setText("Password");
    register_passwordField.setToolTipText("");
    register_passwordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    register_passwordField.setMargin(new java.awt.Insets(0, 20, 0, 20));
    register_passwordField.setOpaque(false);
    panel_register_container.add(register_passwordField);

    register_emailField.setBackground(new Color(0,0,0,0));
    register_emailField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    register_emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    register_emailField.setText("Email");
    register_emailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    register_emailField.setMargin(new java.awt.Insets(0, 20, 0, 20));
    register_emailField.setMinimumSize(new java.awt.Dimension(40, 24));
    register_emailField.setOpaque(false);
    register_emailField.setPreferredSize(new java.awt.Dimension(88, 40));
    panel_register_container.add(register_emailField);

    register_registerButton.setBackground(new java.awt.Color(255, 255, 255));
    register_registerButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    register_registerButton.setText("Sign up");
    register_registerButton.setToolTipText("");
    register_registerButton.setBorder(new CompoundBorder(
        BorderFactory.createEmptyBorder(10, 50, 0, 50), 
        BorderFactory.createMatteBorder(0,0,2,0 , Color.BLACK)));
register_registerButton.setContentAreaFilled(false);
register_registerButton.setMargin(new java.awt.Insets(20, 20, 20, 20));
register_registerButton.setPreferredSize(new java.awt.Dimension(29, 10));
panel_register_container.add(register_registerButton);

panel_register.add(panel_register_container, java.awt.BorderLayout.SOUTH);

register_backToLoginButton.setText("< Login");
register_backToLoginButton.setBorderPainted(false);
register_backToLoginButton.setContentAreaFilled(false);
register_backToLoginButton.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        register_backToLoginButtonActionPerformed(evt);
    }
    });
    panel_register.add(register_backToLoginButton, java.awt.BorderLayout.NORTH);

    panel_main.add(panel_register, "card_register");

    panel_coffeeList.setOpaque(false);
    panel_coffeeList.setLayout(new java.awt.BorderLayout());

    jButton1.setText("< login");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    panel_coffeeList.add(jButton1, java.awt.BorderLayout.NORTH);

    panel_coffeelist_left.setOpaque(false);

    coffeelist_coffeelisLabel.setText("Coffee List");

    javax.swing.GroupLayout panel_coffeelist_leftLayout = new javax.swing.GroupLayout(panel_coffeelist_left);
    panel_coffeelist_left.setLayout(panel_coffeelist_leftLayout);
    panel_coffeelist_leftLayout.setHorizontalGroup(
        panel_coffeelist_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_coffeelist_leftLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(coffeelist_coffeelisLabel)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    panel_coffeelist_leftLayout.setVerticalGroup(
        panel_coffeelist_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_coffeelist_leftLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(coffeelist_coffeelisLabel)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    panel_coffeeList.add(panel_coffeelist_left, java.awt.BorderLayout.WEST);

    panel_coffeelist_center.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
    panel_coffeelist_center.setOpaque(false);
    panel_coffeelist_center.setLayout(new java.awt.GridLayout(7, 1, 5, 5));

    panel_header.setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panel_header.add(filler3, gridBagConstraints);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Small");
    jLabel1.setMaximumSize(new java.awt.Dimension(73, 23));
    jLabel1.setMinimumSize(new java.awt.Dimension(73, 23));
    jLabel1.setPreferredSize(new java.awt.Dimension(73, 23));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
    panel_header.add(jLabel1, gridBagConstraints);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Medium");
    jLabel2.setMaximumSize(new java.awt.Dimension(73, 23));
    jLabel2.setMinimumSize(new java.awt.Dimension(73, 23));
    jLabel2.setPreferredSize(new java.awt.Dimension(73, 23));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
    panel_header.add(jLabel2, gridBagConstraints);

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Large");
    jLabel3.setMaximumSize(new java.awt.Dimension(73, 23));
    jLabel3.setMinimumSize(new java.awt.Dimension(73, 23));
    jLabel3.setPreferredSize(new java.awt.Dimension(73, 23));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
    panel_header.add(jLabel3, gridBagConstraints);

    panel_coffeelist_center.add(panel_header);

    panel_row1.setOpaque(false);
    panel_row1.setLayout(new java.awt.GridBagLayout());

    jButton2.setText("jButton2");
    jButton2.setMaximumSize(new java.awt.Dimension(50, 50));
    jButton2.setMinimumSize(new java.awt.Dimension(50, 50));
    jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panel_row1.add(jButton2, gridBagConstraints);

    jButton3.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row1.add(jButton3, gridBagConstraints);

    jButton4.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row1.add(jButton4, gridBagConstraints);

    jButton5.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row1.add(jButton5, gridBagConstraints);

    panel_coffeelist_center.add(panel_row1);

    panel_row2.setOpaque(false);
    panel_row2.setLayout(new java.awt.GridBagLayout());

    jButton6.setText("jButton2");
    jButton6.setMaximumSize(new java.awt.Dimension(50, 50));
    jButton6.setMinimumSize(new java.awt.Dimension(50, 50));
    jButton6.setPreferredSize(new java.awt.Dimension(50, 50));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panel_row2.add(jButton6, gridBagConstraints);

    jButton7.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row2.add(jButton7, gridBagConstraints);

    jButton8.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row2.add(jButton8, gridBagConstraints);

    jButton9.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row2.add(jButton9, gridBagConstraints);

    panel_coffeelist_center.add(panel_row2);

    panel_row3.setOpaque(false);
    panel_row3.setLayout(new java.awt.GridBagLayout());

    jButton10.setText("jButton2");
    jButton10.setMaximumSize(new java.awt.Dimension(50, 50));
    jButton10.setMinimumSize(new java.awt.Dimension(50, 50));
    jButton10.setPreferredSize(new java.awt.Dimension(50, 50));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panel_row3.add(jButton10, gridBagConstraints);

    jButton11.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row3.add(jButton11, gridBagConstraints);

    jButton12.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row3.add(jButton12, gridBagConstraints);

    jButton13.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row3.add(jButton13, gridBagConstraints);

    panel_coffeelist_center.add(panel_row3);

    panel_row4.setOpaque(false);
    panel_row4.setLayout(new java.awt.GridBagLayout());

    jButton14.setText("jButton2");
    jButton14.setMaximumSize(new java.awt.Dimension(50, 50));
    jButton14.setMinimumSize(new java.awt.Dimension(50, 50));
    jButton14.setPreferredSize(new java.awt.Dimension(50, 50));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panel_row4.add(jButton14, gridBagConstraints);

    jButton15.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row4.add(jButton15, gridBagConstraints);

    jButton16.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row4.add(jButton16, gridBagConstraints);

    jButton17.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row4.add(jButton17, gridBagConstraints);

    panel_coffeelist_center.add(panel_row4);

    panel_row5.setOpaque(false);
    panel_row5.setLayout(new java.awt.GridBagLayout());

    jButton18.setText("jButton2");
    jButton18.setMaximumSize(new java.awt.Dimension(50, 50));
    jButton18.setMinimumSize(new java.awt.Dimension(50, 50));
    jButton18.setPreferredSize(new java.awt.Dimension(50, 50));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panel_row5.add(jButton18, gridBagConstraints);

    jButton19.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row5.add(jButton19, gridBagConstraints);

    jButton20.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row5.add(jButton20, gridBagConstraints);

    jButton21.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row5.add(jButton21, gridBagConstraints);

    panel_coffeelist_center.add(panel_row5);

    panel_row6.setOpaque(false);
    panel_row6.setLayout(new java.awt.GridBagLayout());

    jButton22.setText("jButton2");
    jButton22.setMaximumSize(new java.awt.Dimension(50, 50));
    jButton22.setMinimumSize(new java.awt.Dimension(50, 50));
    jButton22.setPreferredSize(new java.awt.Dimension(50, 50));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    panel_row6.add(jButton22, gridBagConstraints);

    jButton23.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row6.add(jButton23, gridBagConstraints);

    jButton24.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row6.add(jButton24, gridBagConstraints);

    jButton25.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    panel_row6.add(jButton25, gridBagConstraints);

    panel_coffeelist_center.add(panel_row6);

    panel_coffeeList.add(panel_coffeelist_center, java.awt.BorderLayout.CENTER);

    panel_main.add(panel_coffeeList, "card_coffeelist");

    javax.swing.GroupLayout panel_orderReviewLayout = new javax.swing.GroupLayout(panel_orderReview);
    panel_orderReview.setLayout(panel_orderReviewLayout);
    panel_orderReviewLayout.setHorizontalGroup(
        panel_orderReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 480, Short.MAX_VALUE)
    );
    panel_orderReviewLayout.setVerticalGroup(
        panel_orderReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 800, Short.MAX_VALUE)
    );

    panel_main.add(panel_orderReview, "card_orderreview");

    javax.swing.GroupLayout panel_rateLayout = new javax.swing.GroupLayout(panel_rate);
    panel_rate.setLayout(panel_rateLayout);
    panel_rateLayout.setHorizontalGroup(
        panel_rateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 480, Short.MAX_VALUE)
    );
    panel_rateLayout.setVerticalGroup(
        panel_rateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 800, Short.MAX_VALUE)
    );

    panel_main.add(panel_rate, "card_rate");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_createAccountButtonActionPerformed
        CardLayout cards = (CardLayout)panel_main.getLayout();
        cards.show(panel_main, "card_register");
    }//GEN-LAST:event_login_createAccountButtonActionPerformed

    private void register_backToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_backToLoginButtonActionPerformed
        CardLayout cards = (CardLayout)panel_main.getLayout();
        cards.show(panel_main, "card_login");
    }//GEN-LAST:event_register_backToLoginButtonActionPerformed

    private void login_loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_loginButtonActionPerformed
        CardLayout cards = (CardLayout)panel_main.getLayout();
        cards.show(panel_main, "card_coffeelist");
    }//GEN-LAST:event_login_loginButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cards = (CardLayout)panel_main.getLayout();
        cards.show(panel_main, "card_login");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coffeelist_coffeelisLabel;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login_createAccountButton;
    private javax.swing.JButton login_forgotPasswordButton;
    private javax.swing.JButton login_loginButton;
    private javax.swing.JLabel login_loginWithLabel;
    private javax.swing.JTextField login_passwordField;
    private javax.swing.JTextField login_usernameField;
    private javax.swing.JPanel panel_coffeeList;
    private javax.swing.JPanel panel_coffeelist_center;
    private javax.swing.JPanel panel_coffeelist_left;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_login_container;
    private javax.swing.JPanel panel_login_container_register;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_orderReview;
    private javax.swing.JPanel panel_rate;
    private javax.swing.JPanel panel_register;
    private javax.swing.JPanel panel_register_container;
    private javax.swing.JPanel panel_row1;
    private javax.swing.JPanel panel_row2;
    private javax.swing.JPanel panel_row3;
    private javax.swing.JPanel panel_row4;
    private javax.swing.JPanel panel_row5;
    private javax.swing.JPanel panel_row6;
    private javax.swing.JButton register_backToLoginButton;
    private javax.swing.JTextField register_emailField;
    private javax.swing.JTextField register_passwordField;
    private javax.swing.JButton register_registerButton;
    private javax.swing.JTextField register_usernameField;
    // End of variables declaration//GEN-END:variables
}
