/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smegi.coffeeshop;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.CompoundBorder;

/**
 *
 * @author Pakijaner
 */
public class CoffeeShop extends javax.swing.JFrame {

    /**
     * Creates new form CoffeeShop
     */
    public CoffeeShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_main = new javax.swing.JPanel();
        javax.swing.JPanel panel_login = new JPanelBackground("/background.jpg");
        login_loginWithLabel = new javax.swing.JLabel();
        panel_login_container = new javax.swing.JPanel();
        login_usernameField = new javax.swing.JTextField();
        login_passwordField = new javax.swing.JTextField();
        login_loginButton = new javax.swing.JButton();
        panel_login_container_register = new javax.swing.JPanel();
        login_createAccountButton = new javax.swing.JButton();
        login_forgotPasswordButton = new javax.swing.JButton();
        panel_register = new javax.swing.JPanel();
        panel_register_container = new javax.swing.JPanel();
        register_usernameField = new javax.swing.JTextField();
        register_passwordField = new javax.swing.JTextField();
        register_emailField = new javax.swing.JTextField();
        register_registerButton = new javax.swing.JButton();
        register_backToLoginButton = new javax.swing.JButton();
        panel_coffeeList = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panel_coffeelist_left = new javax.swing.JPanel();
        coffeelist_coffeelisLabel = new javax.swing.JLabel();
        panel_coffeelist_center = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panel_orderReview = new javax.swing.JPanel();
        panel_rate = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("loginFrame"); // NOI18N

        panel_main.setMinimumSize(new java.awt.Dimension(0, 0));
        panel_main.setPreferredSize(new java.awt.Dimension(480, 800));
        panel_main.setLayout(new java.awt.CardLayout());

        panel_login.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 50, 10, 50));
        panel_login.setPreferredSize(new java.awt.Dimension(480, 800));
        panel_login.setLayout(new java.awt.BorderLayout());

        login_loginWithLabel.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        login_loginWithLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_loginWithLabel.setText("login with");
        panel_login.add(login_loginWithLabel, java.awt.BorderLayout.CENTER);

        panel_login_container.setOpaque(false);
        panel_login_container.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        login_usernameField.setBackground(new Color(0,0,0,0));
        login_usernameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_usernameField.setText("Username");
        login_usernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        login_usernameField.setMargin(new java.awt.Insets(0, 20, 0, 20));
        login_usernameField.setMinimumSize(new java.awt.Dimension(40, 24));
        login_usernameField.setOpaque(false);
        login_usernameField.setPreferredSize(new java.awt.Dimension(88, 40));
        panel_login_container.add(login_usernameField);

        login_passwordField.setBackground(new Color(0,0,0,0));
        login_passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_passwordField.setText("Password");
        login_passwordField.setToolTipText("");
        login_passwordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        login_passwordField.setMargin(new java.awt.Insets(0, 20, 0, 20));
        login_passwordField.setOpaque(false);
        panel_login_container.add(login_passwordField);

        login_loginButton.setBackground(new java.awt.Color(255, 255, 255));
        login_loginButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_loginButton.setText("Login");
        login_loginButton.setToolTipText("");
        login_loginButton.setBorder(new CompoundBorder(
            BorderFactory.createEmptyBorder(10, 50, 0, 50), 
            BorderFactory.createMatteBorder(0,0,2,0 , Color.BLACK)));
    login_loginButton.setContentAreaFilled(false);
    login_loginButton.setMargin(new java.awt.Insets(20, 20, 20, 20));
    login_loginButton.setPreferredSize(new java.awt.Dimension(29, 10));
    login_loginButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            login_loginButtonActionPerformed(evt);
        }
    });
    panel_login_container.add(login_loginButton);

    panel_login_container_register.setOpaque(false);
    panel_login_container_register.setLayout(new java.awt.GridLayout(1, 0, 100, 0));

    login_createAccountButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    login_createAccountButton.setText("Create an account");
    login_createAccountButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    login_createAccountButton.setContentAreaFilled(false);
    login_createAccountButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            login_createAccountButtonActionPerformed(evt);
        }
    });
    panel_login_container_register.add(login_createAccountButton);

    login_forgotPasswordButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    login_forgotPasswordButton.setText("Forgot password");
    login_forgotPasswordButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    login_forgotPasswordButton.setContentAreaFilled(false);
    panel_login_container_register.add(login_forgotPasswordButton);

    panel_login_container.add(panel_login_container_register);

    panel_login.add(panel_login_container, java.awt.BorderLayout.SOUTH);

    panel_main.add(panel_login, "card_login");

    panel_register.setLayout(new java.awt.BorderLayout());

    panel_register_container.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

    register_usernameField.setBackground(new java.awt.Color(240, 240, 240));
    register_usernameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    register_usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    register_usernameField.setText("Username");
    register_usernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    register_usernameField.setMargin(new java.awt.Insets(0, 20, 0, 20));
    register_usernameField.setMinimumSize(new java.awt.Dimension(300, 24));
    register_usernameField.setPreferredSize(new java.awt.Dimension(88, 40));
    panel_register_container.add(register_usernameField);

    register_passwordField.setBackground(new java.awt.Color(240, 240, 240));
    register_passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    register_passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    register_passwordField.setText("Password");
    register_passwordField.setToolTipText("");
    register_passwordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    register_passwordField.setMargin(new java.awt.Insets(0, 20, 0, 20));
    panel_register_container.add(register_passwordField);

    register_emailField.setBackground(new java.awt.Color(240, 240, 240));
    register_emailField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    register_emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    register_emailField.setText("Email");
    register_emailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
    register_emailField.setMargin(new java.awt.Insets(0, 20, 0, 20));
    register_emailField.setMinimumSize(new java.awt.Dimension(40, 24));
    register_emailField.setPreferredSize(new java.awt.Dimension(88, 40));
    panel_register_container.add(register_emailField);

    register_registerButton.setBackground(new java.awt.Color(255, 255, 255));
    register_registerButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    register_registerButton.setText("Sign up");
    register_registerButton.setToolTipText("");
    register_registerButton.setBorder(new CompoundBorder(
        BorderFactory.createEmptyBorder(10, 50, 0, 50), 
        BorderFactory.createMatteBorder(0,0,2,0 , Color.BLACK)));
register_registerButton.setContentAreaFilled(false);
register_registerButton.setMargin(new java.awt.Insets(20, 20, 20, 20));
register_registerButton.setPreferredSize(new java.awt.Dimension(29, 10));
panel_register_container.add(register_registerButton);

panel_register.add(panel_register_container, java.awt.BorderLayout.EAST);

register_backToLoginButton.setText("< Login");
register_backToLoginButton.setBorderPainted(false);
register_backToLoginButton.setContentAreaFilled(false);
register_backToLoginButton.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        register_backToLoginButtonActionPerformed(evt);
    }
    });
    panel_register.add(register_backToLoginButton, java.awt.BorderLayout.NORTH);

    panel_main.add(panel_register, "card_register");

    panel_coffeeList.setLayout(new java.awt.BorderLayout());

    jButton1.setText("< login");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    panel_coffeeList.add(jButton1, java.awt.BorderLayout.NORTH);

    coffeelist_coffeelisLabel.setText("Coffee List");

    javax.swing.GroupLayout panel_coffeelist_leftLayout = new javax.swing.GroupLayout(panel_coffeelist_left);
    panel_coffeelist_left.setLayout(panel_coffeelist_leftLayout);
    panel_coffeelist_leftLayout.setHorizontalGroup(
        panel_coffeelist_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_coffeelist_leftLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(coffeelist_coffeelisLabel)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    panel_coffeelist_leftLayout.setVerticalGroup(
        panel_coffeelist_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_coffeelist_leftLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(coffeelist_coffeelisLabel)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    panel_coffeeList.add(panel_coffeelist_left, java.awt.BorderLayout.WEST);

    panel_coffeelist_center.setLayout(new java.awt.GridLayout(7, 1, 5, 5));

    jPanel1.setLayout(new java.awt.GridBagLayout());

    jButton2.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    jPanel1.add(jButton2, gridBagConstraints);

    jButton3.setText("jButton2");
    jPanel1.add(jButton3, new java.awt.GridBagConstraints());

    jButton4.setText("jButton2");
    jPanel1.add(jButton4, new java.awt.GridBagConstraints());

    jButton5.setText("jButton2");
    jPanel1.add(jButton5, new java.awt.GridBagConstraints());

    panel_coffeelist_center.add(jPanel1);

    panel_coffeeList.add(panel_coffeelist_center, java.awt.BorderLayout.CENTER);

    panel_main.add(panel_coffeeList, "card_coffeelist");

    javax.swing.GroupLayout panel_orderReviewLayout = new javax.swing.GroupLayout(panel_orderReview);
    panel_orderReview.setLayout(panel_orderReviewLayout);
    panel_orderReviewLayout.setHorizontalGroup(
        panel_orderReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 480, Short.MAX_VALUE)
    );
    panel_orderReviewLayout.setVerticalGroup(
        panel_orderReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 800, Short.MAX_VALUE)
    );

    panel_main.add(panel_orderReview, "card_orderreview");

    javax.swing.GroupLayout panel_rateLayout = new javax.swing.GroupLayout(panel_rate);
    panel_rate.setLayout(panel_rateLayout);
    panel_rateLayout.setHorizontalGroup(
        panel_rateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 480, Short.MAX_VALUE)
    );
    panel_rateLayout.setVerticalGroup(
        panel_rateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 800, Short.MAX_VALUE)
    );

    panel_main.add(panel_rate, "card_rate");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_createAccountButtonActionPerformed
        CardLayout cards = (CardLayout)panel_main.getLayout();
        cards.show(panel_main, "card_register");
    }//GEN-LAST:event_login_createAccountButtonActionPerformed

    private void register_backToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_backToLoginButtonActionPerformed
        CardLayout cards = (CardLayout)panel_main.getLayout();
        cards.show(panel_main, "card_login");
    }//GEN-LAST:event_register_backToLoginButtonActionPerformed

    private void login_loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_loginButtonActionPerformed
        CardLayout cards = (CardLayout)panel_main.getLayout();
        cards.show(panel_main, "card_coffeelist");
    }//GEN-LAST:event_login_loginButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cards = (CardLayout)panel_main.getLayout();
        cards.show(panel_main, "card_login");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coffeelist_coffeelisLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_createAccountButton;
    private javax.swing.JButton login_forgotPasswordButton;
    private javax.swing.JButton login_loginButton;
    private javax.swing.JLabel login_loginWithLabel;
    private javax.swing.JTextField login_passwordField;
    private javax.swing.JTextField login_usernameField;
    private javax.swing.JPanel panel_coffeeList;
    private javax.swing.JPanel panel_coffeelist_center;
    private javax.swing.JPanel panel_coffeelist_left;
    private javax.swing.JPanel panel_login_container;
    private javax.swing.JPanel panel_login_container_register;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_orderReview;
    private javax.swing.JPanel panel_rate;
    private javax.swing.JPanel panel_register;
    private javax.swing.JPanel panel_register_container;
    private javax.swing.JButton register_backToLoginButton;
    private javax.swing.JTextField register_emailField;
    private javax.swing.JTextField register_passwordField;
    private javax.swing.JButton register_registerButton;
    private javax.swing.JTextField register_usernameField;
    // End of variables declaration//GEN-END:variables
}
